[package]
name = "pdf-procuracion"
version = "0.1.0"
edition = "2021"

[dependencies]
lopdf = "0.34"
regex = "1"
calamine = "0.26"
rust_xlsxwriter = "0.80"
rfd = "0.15"

[build-dependencies]
winres = "0.1"

